Upgrade to 16.0
duitkupg/odoo-payment_duitku pull request #3
Opened 2023-08-19 08:47 UTC by wm-cortex

Due to the changes in Odoo Oline payment API, I have upgraded it to Odoo 16.0 with the new payment API.

2023-08-21 11:18 UTC, wm-cortex commented
@KangLeian Could you please test the upgraded app from your side?

2023-08-23 10:32 UTC, KangLeian requested changes
Adding a validation before changing the status payment.

2023-08-23 10:32 UTC, KangLeian commented on models/payment_transaction.py
> +        if payment_status == '00':
Hi @wm-cortex  , Please add signature validation and check transaction validation before processing here.

2023-08-24 02:16 UTC, KangLeian approved these changes
Awesome, Thank you for the updates!

2023-08-24 02:20 UTC, merged

2023-08-24 12:19 UTC, wm-cortex commented
@KangLeian Thanks for merging.